[PPANTT-135] chore: defined re schema
pagopa/pagopa-payment-options-service pull request #8
Opened 2024-09-24 15:59 UTC by gioelemella

#### List of Changes

- defined payment-options-re json schema

#### Motivation and Context
PPANTT-1https://pagopa.atlassian.net/browse/PPANTT-13535

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-09-25 07:12 UTC, svariant approved these changes

2024-09-26 07:47 UTC, jacopocarlini approved these changes

2024-09-26 08:52 UTC, pasqualespica requested changes
lgtm 🆗 
evaluate some change proposal

2024-09-26 08:52 UTC, pasqualespica commented on templates/payment-options-re.json
> +          "description": "Id dell’EC"
force len to `11` https://json-schema.org/understanding-json-schema/reference/string#length

2024-09-26 08:52 UTC, pasqualespica commented on templates/payment-options-re.json
> +          "description": "Id del PSP"
ditto as for `organizationId`

2024-09-26 08:52 UTC, pasqualespica commented on templates/payment-options-re.json
> +        "iuv": {
for iuv and notice could be use https://json-schema.org/understanding-json-schema/reference/regular_expressions ? right @jacopocarlini @aomegax @marilenapaldino87 ?

2024-09-26 08:52 UTC, pasqualespica commented on templates/payment-options-re.json
> +        "errorStatusCode": {
it its our ODP-<error> use use regex- livk "ODP-" + 4 digits example
and add link to ODP open-api as legend
https://json-schema.org/learn/miscellaneous-examples#regular-expression-pattern

2024-09-26 08:52 UTC, pasqualespica commented on templates/payment-options-re.json
> +          "type": "string"
add description to specify encoding ( base64, gzip , ... )

2024-09-26 08:52 UTC, pasqualespica commented on templates/payment-options-re.json
> +        "version": {
number `1`, ...

2024-09-26 08:52 UTC, pasqualespica commented on templates/payment-options-re.json
> +          "description": "Data inserimento evento su kafka",
into to descriptio specify datatime format type

2024-09-30 08:23 UTC, merged